# -*- coding: utf-8 -*-
"""CodecuoiKi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11i-J4XeHxTZ_mzClWjrEnRlC5d9ayt-9
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

data= pd.read_csv('/content/thoitiet4.csv' , encoding='latin1')

data['datetime'] = pd.to_datetime(data['datetime'])
print(data)

data['month'] = data['datetime'].dt.month
data['year'] = data['datetime'].dt.year
data['year_month'] = data['datetime'].dt.to_period('M')
monthly_data = data.groupby('year_month').agg({
    'tempmax': 'mean',
    'tempmin': 'mean',
    'temp': 'mean',
    'precip': 'sum',
}).reset_index()
fig, ax1 = plt.subplots(figsize=(12, 6))
ax1.plot(monthly_data['year_month'].astype(str), monthly_data['tempmax'], label='Nhiệt  độ lớn nhất', color='red')
ax1.plot(monthly_data['year_month'].astype(str), monthly_data['tempmin'], label='Nhiệt độ min', color='blue')
ax1.plot(monthly_data['year_month'].astype(str), monthly_data['temp'], label='Nhiệt độ trung bình', color='green')
ax1.set_xlabel('Thời gian')
ax1.set_ylabel('Nhiệt độ (°C)')
ax1.set_title('Thời tiết tổng quan')
ax1.legend(loc='upper left')
ax2 = ax1.twinx()
ax2.plot(monthly_data['year_month'].astype(str), monthly_data['precip'], label='Lượng mưa (mm)', color='purple', linestyle='--')
ax2.set_ylabel('Lượng mưa (mm)')
ax2.legend(loc='upper right')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

uv_title = []
for i in range(len(data)):
  if(data['uvindex'][i] >= 0) and (data['uvindex'][i] <= 2):
    uv_title.append('Thap')
  elif (data['uvindex'][i] >2) and (data['uvindex'][i] <=5):
    uv_title.append('Trung Binh')
  elif (data['uvindex'][i] >5) and (data['uvindex'][i] <= 7):
    uv_title.append('Cao')
  elif (data['uvindex'][i] >7) and (data['uvindex'][i] <= 10):
    uv_title.append('Rat Cao')
  else:
    uv_title.append('Cuc ki cao')
data['UV_TITLE'] = uv_title

uv_thang1 = data[data['datetime'].dt.month == 1].UV_TITLE
uv_thang2 = data[data['datetime'].dt.month == 2].UV_TITLE
uv_thang3 = data[data['datetime'].dt.month == 3].UV_TITLE
uv_thang4 = data[data['datetime'].dt.month == 4].UV_TITLE
print(uv_thang2)
data.reset_index(inplace = True)
nhietdo_thang2 = data[data['datetime'].dt.month == 2].temp
print(nhietdo_thang2)

import matplotlib.pyplot as plt
import pandas as pd

uv_thang1 = pd.Series(['cao', 'rất cao', 'thấp', 'trung bình', 'cao', 'thấp', 'cao', 'rất cao'])
uv_thang2 = pd.Series(['cao', 'rất cao', 'thấp', 'trung bình', 'thấp', 'trung bình', 'cao'])
uv_thang3 = pd.Series(['cao', 'rất cao', 'thấp', 'trung bình', 'thấp', 'cao'])
uv_thang4 = pd.Series(['cao', 'rất cao', 'thấp', 'trung bình', 'cao', 'trung bình'])


uv_cnts1 = uv_thang1.value_counts()
uv_cnts2 = uv_thang2.value_counts()
uv_cnts3 = uv_thang3.value_counts()
uv_cnts4 = uv_thang4.value_counts()


labels = ['cao', 'trung bình', 'rất cao', 'thấp']
colors = ['#ff9999','#66b3ff','#99ff99','#ffcc99']
color_dict = dict(zip(labels, colors))
ranked_labels = ['rất cao', 'cao', 'trung bình', 'thấp']
ranked_colors = [color_dict[label] for label in ranked_labels]


def get_colors(data, color_dict):
    return [color_dict[label] for label in data.index]

fig, ax = plt.subplots(2, 2, figsize=(12, 6))

# Biểu đồ tròn thứ nhất
ax[0, 0].pie(uv_cnts1, labels=['']*len(uv_cnts1), colors=get_colors(uv_cnts1, color_dict), autopct='%1.1f%%', startangle=140)
ax[0, 0].axis('equal')
ax[0,0].set_title('Tháng 1')

# Biểu đồ tròn thứ hai
ax[0, 1].pie(uv_cnts2, labels=['']*len(uv_cnts2), colors=get_colors(uv_cnts2, color_dict), autopct='%1.1f%%', startangle=140)
ax[0, 1].axis('equal')
ax[0,1].set_title('Tháng 2')

# Biểu đồ tròn thứ ba
ax[1, 0].pie(uv_cnts3, labels=['']*len(uv_cnts3), colors=get_colors(uv_cnts3, color_dict), autopct='%1.1f%%', startangle=140)
ax[1, 0].axis('equal')
ax[1,0].set_title('Tháng 3')

# Biểu đồ tròn thứ tư
ax[1, 1].pie(uv_cnts4, labels=['']*len(uv_cnts4), colors=get_colors(uv_cnts4, color_dict), autopct='%1.1f%%', startangle=140)
ax[1, 1].axis('equal')
ax[1,1].set_title('Tháng 4')
handles = [plt.Line2D([0], [0], marker='o', color='w', markerfacecolor=color, markersize=10) for color in ranked_colors]
plt.legend(handles, ranked_labels, loc="upper left", bbox_to_anchor=(1, 1))
plt.suptitle('Biểu đồ UV tháng 1 đến tháng 4')
plt.tight_layout()
plt.show()

#biểu đồ nhiệt độ lớn nhất, nhỏ nhất, nhiệt độ từng ngày
plt.figure(figsize=(12, 6))
plt.plot(data['datetime'], data['temp'], label='Nhiệt độ trung bình')
plt.plot(data['datetime'], data['tempmax'], label='Nhiệt độ cao nhất')
plt.plot(data['datetime'], data['tempmin'], label='Nhiệt độ thấp nhất')
plt.xlabel('Ngày')
plt.ylabel('Nhiệt độ (°C)')
plt.title('Nhiệt độ hàng ngày theo thời gian')
plt.legend()
plt.show()

#biểu đồ cột lượng mưa theo thời gian
fig1 = plt.subplots( figsize= (12,6))
plt.bar(data['datetime'], data['precip'], color='blue')
plt.xlabel('Ngày')
plt.ylabel('Lượng mưa (mm)')
plt.title('Lượng mưa hàng ngày')

data_temp=data['temp']
datahumidity = data['humidity']
data_time = data['datetime']
feelslike = data['feelslike']

sns.scatterplot(y=data_temp, x=data['dew'], hue = data['precipprob'], palette = 'Set2')
plt.ylabel('Nhiệt độ(°C)')
plt.xlabel('Sương mù(%)')
plt.title('Nhiệt độ và sương mù')
plt.tight_layout()

data_temp=data['temp']
nhietdo_thang2 = data[data['datetime'].dt.month == 2].temp
doam_thang2 = data[data['datetime'].dt.month == 2].humidity
data_humidity = data['humidity']
data_time = data[data['datetime'].dt.month == 2].datetime
fig, ax1 = plt.subplots(figsize=(12,6))
ax1.set_xlabel('Thời gian')
ax1.set_ylabel('Nhiệt độ(°C)', color ='tab:red')
ax1.plot(data_time,nhietdo_thang2, color ='tab:red', label='Nhiệt độ')
ax1.tick_params(axis='y', labelcolor='tab:red')
ax2 = ax1.twinx()
ax2.set_ylabel('Độ ẩm(%)', color ='tab:blue')
ax2.plot(data_time, doam_thang2, color ='tab:blue', label='Độ ẩm')
ax2.tick_params(axis ='y', labelcolor='tab:blue')
plt.title('Nhiệt độ và Độ ẩm')
fig.tight_layout()
plt.show()

data_dew=data['dew']
suongmu_thang2 = data[data['datetime'].dt.month == 2].dew
data_visibility = data['visibility']
tamnhin_thang2 = data[data['datetime'].dt.month == 2].visibility
data_time = data[data['datetime'].dt.month == 2].datetime
fig, ax1 = plt.subplots(figsize=(12,6))
ax1.set_xlabel('Thời gian')
ax1.set_ylabel('Sương mù(%)', color ='tab:red')
ax1.plot(data_time,suongmu_thang2, color ='tab:red', label='Sương mù')
ax1.tick_params(axis='y', labelcolor='tab:red')
ax2 = ax1.twinx()
ax2.set_ylabel('Tầm nhìn(km)', color ='tab:blue')
ax2.plot(data_time, tamnhin_thang2, color ='tab:blue', label='Tầm nhìn')
ax2.tick_params(axis ='y', labelcolor='tab:blue')
plt.title('Tầm nhìn và sương mù')
fig.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import pandas as pd

file_path = '/content/thoitiet4.csv'
weather_data = pd.read_csv('thoitiet4.csv', encoding = 'latin1')
columns = ['tempmax', 'tempmin', 'temp', 'feelslike']
colors = ['lightblue', 'lightgreen', 'lightcoral', 'lightskyblue']

plt.figure(figsize=(10, 6))

box = plt.boxplot([weather_data[col] for col in columns], patch_artist=True, labels=columns)
for patch, color in zip(box['boxes'], colors):
    patch.set_facecolor(color)
plt.title('Boxplot của Các Loại Nhiệt Độ')
plt.ylabel('Nhiệt Độ (°C)')
plt.xlabel('Loại Đo Lường')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt


if 'humidity' in data.columns:
    plt.figure(figsize=(10, 6))
    sns.histplot(data['humidity'], bins=30, kde=True)
    plt.title('Biểu đồ Histogram cho Độ ẩm')
    plt.xlabel('Độ ẩm (%)')
    plt.ylabel('Tần suất')
    plt.show()
else:
    print("Cột 'humidity' không tồn tại trong dữ liệu.")

!pip install windrose

from windrose import WindroseAxes
fig= plt.figure(figsize=(10,4))
if 'winddir' in data.columns and 'windspeed' in data.columns:
    ax = WindroseAxes.from_ax()
    ax.bar(data['winddir'], data['windspeed'], normed=True, opening=0.8, edgecolor='white')
    ax.set_title('Biểu đồ hướng gió và tốc độ gió')
    ax.set_legend(title="Tốc độ gió (m/s)")
    plt.show()
else:
    print("Cột 'winddir' hoặc 'windspeed' không tồn tại trong dữ liệu.")